### ISSUE TITLE
Broken PPA on latest ElementaryOS

### ISSUE THREAD

**Issue by nathanernest** [elementary-tweaks/elementary-tweaks#152]
Latest version of ElementaryOS (hera) won't allow installation of PPA.

`Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 107, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 117, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 612, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: **Error: could not find a distribution template for elementary/hera**`

**Comment by nathanernest** [comment]
After updating and restarting this seems to have fixed itself. Closing.
